trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt
    rust_version: stable 

- job: test
  displayName: Test
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
  pool:
    vmImage: $(vmImage)
  steps:
    - template: ci/azure-install-rust.yml
      parameters:
        rust_version: stable 
    - script: RUSTFLAGS="-D warnings" cargo test --all --all-features
      displayName: cargo test --all --all-features
