[package]
name = "clique"
version = "0.1.0"
authors = [
  "Lucio Franco <luciofranco14@gmail.com>",
  "Bhargav Voleti <bhargav.voleti93@gmail.com>"
]
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
tokio-timer = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio-trace = { git = "https://github.com/tokio-rs/tokio" }
uuid = { version = "0.7", features = ["serde", "v4"] }
cuckoofilter = "0.3"
indexmap = "1.0"
rand = "0.6"
bincode = "1.1"
rand = "0.6"

[dev-dependencies]
tokio-test = { git = "https://github.com/LucioFranco/tokio", branch = "tokio-test" }
quickcheck = "0.8"
