[package]
name = "clique"
version = "0.1.0"
authors = [
  "Lucio Franco <luciofranco14@gmail.com>",
  "Bhargav Voleti <bhargav.voleti93@gmail.com>"
]
edition = "2018"
publish = false

[dependencies]
futures-preview = "0.3.0-alpha.16"

[dev-dependencies]
tokio = { git = "https://github.com/LucioFranco/tokio" }
tokio-test = { git = "https://github.com/tokio-rs/tokio" }
