[package]
name = "clique"
version = "0.1.0"
authors = [
  "Lucio Franco <luciofranco14@gmail.com>",
  "Bhargav Voleti <bhargav.voleti93@gmail.com>"
]
edition = "2018"
publish = false

[workspace]
members = ["clique-grpc"]

[dependencies]
bytes = "0.4"
futures = { version = "=0.3.0-alpha.17", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = "1.0"
tokio-sync = { git = "https://github.com/tokio-rs/tokio", features = ["async-traits"] }
tokio-timer = { git = "https://github.com/tokio-rs/tokio", features = ["async-traits"] }
twox-hash = "1.4"
rand = "0.7.0"
tracing = "0.1"

[dev-dependencies]
tokio = { git = "https://github.com/LucioFranco/tokio" }
tokio-test = { git = "https://github.com/tokio-rs/tokio" }
