[package]
name = "integ-tests"
version = "0.1.0"
authors = ["Bhargav Voleti <voletibv@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clique = { path = "../"}
clique-tonic = { path = "../clique-tonic" }