jobs:
# Check formatting
- job: ${{ parameters.name }}
  displayName: Check rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-install-rust.yml
      parameters:
        rust_version: nightly-2019-06-12
    - script: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting
